CREATE DATABASE ROLLINGPARTY;
USE ROLLINGPARTY;

CREATE TABLE Usuarios(
ID_U INT NOT NULL,
NOM_U VARCHAR(50),
ApPAT_U VARCHAR(50),
ApMAT_U VARCHAR(50),
TEL_U INT(11),
CALLE_U VARCHAR(50),
COL_U VARCHAR(50),
MUN_U VARCHAR(50),
CP_U INT(5),
EMAIL_U VARCHAR(20),
PRIMARY KEY(ID_U)
)ENGINE=INNODB;

CREATE TABLE Servicios(
ID_S INT NOT NULL,
FECHA_S DATE,
HORA_S TIME,
DESCRIPCION_S VARCHAR(50),
PRIMARY KEY(ID_S)
)ENGINE=INNODB;

CREATE TABLE Vehiculos(
ID_V INT NOT NULL,
MATRICULA_V INT(10),
MODELO_V VARCHAR(50),
NUMSEGURO_V INT(50),
PRIMARY KEY(ID_V)
)ENGINE=INNODB;

CREATE TABLE Paquetes(
ID_P INT NOT NULL,
NOM_P VARCHAR(50),
TIPO_P VARCHAR(20),
PRECIO_P FLOAT(6),
DESCRIPCION_P VARCHAR(50),
PRIMARY KEY(ID_P),
ID_V1 INT NOT NULL,
CONSTRAINT fkPaquetes_Vehiculos
FOREIGN KEY(ID_V1)
REFERENCES Vehiculos(ID_V)
)ENGINE=INNODB;

CREATE TABLE Servicios_Usuarios(
ID_S1 INT NOT NULL,
ID_U1 INT NOT NULL,
PRIMARY KEY(ID_S1,ID_U1),
CONSTRAINT fkServicios_Usuarios
FOREIGN KEY (ID_U1)
REFERENCES Usuarios(ID_U),
CONSTRAINT fkUsuarios_Servicios
FOREIGN KEY (ID_S1)
REFERENCES Servicios(ID_S)
)ENGINE=INNODB;

CREATE TABLE Serv_Paq(
ID_S1 INT NOT NULL,
ID_P1 INT NOT NULL,
PRIMARY KEY(ID_S1,ID_P1),
CONSTRAINT fkServicios_Paquetes
FOREIGN KEY (ID_P1)
REFERENCES Paquetes(ID_P),
CONSTRAINT fkPaquetes_Servicios
FOREIGN KEY (ID_S1)
REFERENCES Servicios(ID_S)
)ENGINE=INNODB;

